### ISSUE TITLE
bhai nam ek number he repo ka... 

### ISSUE THREAD

**Issue by hemangjoshi37a** [Parthsadaria/KaamChorGPT#1]
i have tried something similar : https://github.com/hemangjoshi37a/PersonalGoalAssistant
please add a star to this and others .

**Comment by Parthsadaria** [comment]
Haha! Thanks Bhai Your's is a full fledged complete product whilst mine is some jugaad and random python knowledge mixxed up haha thanks again :) i am still learning python from internet and yours will inspire me 🥇
